### ISSUE TITLE
Composer Failure

### ISSUE THREAD

**Issue by alecsmrekar** [bluehorndigital/setup-drupal#13]
When trying to set up Drupal 9.4.1, composer fails when running `create-project`.

It starts out fine.
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/20174058/177481911-93d1a845-8904-4216-adbe-e16d01e07518.png">

But it fails due to the `allowed-plugins` config that's missing.
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/20174058/177481995-5eedc8d6-368c-4601-ac0f-af56575ffffa.png">

**Comment by mglaman** [comment]
This is my current workaround, in workflows:

```
      -   name: Fix allow-plugins (8.9)
          if: ${{ matrix.drupal == '^8.9' }}
          run: |
              cd ~/drupal
              composer config --no-plugins allow-plugins.drupal/core-composer-scaffold true
              composer config --no-plugins allow-plugins.drupal/core-project-message true
      -   name: Fix allow-plugins
          run: |
              cd ~/drupal
              composer config --no-plugins allow-plugins.composer/installers true
              composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
```

I need to get this updated to run this as well.
